version: '3'

services:
  worker:
    image: text-processing
    networks:
      - my_network
    command: python textFunctions.py

networks:
  my_network:
    driver: bridge

#docker-compose up --scale worker=4