version: '3'

services:
  worker:
    image: text-processing
    networks:
      - my_network
    environment:
      - SERVICE_PORT=5000
    ports:
      - "5000"
    command: python textFunctions.py

networks:
  my_network:
    driver: bridge
