version: '3'

services:
  worker:
    image: text-processing
    networks:
      - my_network

  server:
    image: server
    networks:
      - my_network
    command: python server.py
    stdin_open: true
    tty: true

networks:
  my_network:
    driver: bridge